### PR TITLE
display functionname in error

### PR DESCRIPTION
**Pull request by coderofsalvation**
awesome lib, really love the simplicity.
This patch will save lots of debugging time when inspecting logs.
Cheers

### CODE REVIEW

**Comment by timvandam** [comment]
Cool, did not expect anyone to be using this

If you're ever looking to use something more type safe you could check this out: https://deepkit.io/library/rpc

It is still in alpha, but I like it

**Comment by timvandam** [comment]
Seems like there is a dependency error with the `jsdoc` devdependency. Could you set the version to `3.6.3` instead of `^3.6.3`? I'm also guessing that the linter will complain about the lack of spaces around the plusses

**Comment by coderofsalvation** [comment]
Ok, I'll do another PR  (will close this PR)

**Comment by coderofsalvation** [comment]
ps. https://deepkit.io/library/rpc looks very cool, will keep it in mind.
Right now Im working on something more minimal (for lowspec systems): https://github.com/coderofsalvation/elasticnode

**Pull request closed without merging**
